name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Transfer files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BLOG_HOST }}
          username: ${{ secrets.BLOG_USER }}
          port: 22
          password: ${{ secrets.BLOG_PASS }}
          source: "."
          target: "/var/www/html"

      - name: executing laravel deployement commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BLOG_HOST }}
          username: ${{ secrets.BLOG_USER }}
          port: 22
          password: ${{ secrets.BLOG_PASS }}
          script: |
            cd /var/www/html
            echo "creating env file...."
            php -r "file_exists('.env') || copy('.env.example', '.env');"
            echo "executing composer install...."
            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            echo "Granting directory permissions..."
            chmod -R 777 bootstrap/
            chmod -R 777 storage/
            chmod -R 777 public/
            echo "Cache clear..."
            php artisan cache:clear
            echo "done...."
